
[package]
org = "lankawattwise"
name = "lww"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["LankaWattWise Team"]
keywords = ["energy", "ontology", "sri-lanka", "ballerina"]


[build-options]
observabilityIncluded = true

# MySQL JDBC driver configuration for ballerinax/mysql runtime
[platform.java17]
graalvmCompatible = false

[[platform.java17.dependency]]
# MySQL Connector/J (mysql-connector-j) coordinates and local path
path = "libs/mysql-connector-j-8.0.33.jar"
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.0.33"
