
[package]
org = "lankawattwise"
name = "lww"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["LankaWattWise Team"]
keywords = ["energy", "ontology", "sri-lanka", "ballerina"]


[build-options]
observabilityIncluded = true
