version: '3.8'
services:
  fuseki:
    image: stain/jena-fuseki
    ports: ["3030:3030"]
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - ../ontology:/fuseki/ontology
  mqtt:
    image: eclipse-mosquitto
    ports: ["1883:1883"]
  lww_api_gateway:
    build:
      context: ../ballerina
      dockerfile: Dockerfile
    ports: ["9090:9090"]
    depends_on: [fuseki, mqtt]
    environment:
      - BALLERINA_CONFIG_FILE=Config.toml
